### ISSUE TITLE
Fallback 문헌조사

### ISSUE THREAD

**Issue by hyunwoongko** [dialobot/dialobot#10]

**Comment by gityunjae** [comment]
## On Calibration of Modern Neural Networks
Chuan Guo, Geoff Pleiss, Yu Sun, Kilian Q. Weinberger ; Proceedings of the 34th International Conference on Machine Learning, 70:1321-1330, 2017.

## 1. Introduction
- confidence는 모델이 어떤 값을 예측했을 때 그 예측에 얼마나 확신을 가지는지이고, accuracy는 모델이 어떤 값을 예측했을 때 그 값이 얼마나 정확한지를 나타내는 지표
- 보통 이 confidence가 일정 threshold를 넘어가면 그 값을 사용하는 방식
- 현실에서 결정을 내리는 시스템에서 분류 모델은 정확도도 중요하지만 틀릴 수 있는 확률이 어느정도인지도 같이 제시를 해주는게 중요하다
    - 자율주행차에서 앞에 사람이 있는지 방해물이 있는지 탐지하는데 이걸 확실하게 예측할 수 없으면 이걸 알려줘야 확실치 않은 경우에 다른 센서들 출력도 확인을 해서 결정을 한다
    - 암을 진단하는데 암인지 아닌지 확실치 않으면 의사한테 결정권을 넘겨주던지 해야한다
- 그래서 이 confidence를 더 신뢰할 수 있게 하기 위해서 calibrated confidence를 사용하는데, Calibration이란 모형의 출력값이 실제 confidence를 반영하도록 만드는 것을 말하고, 단어 자체는 해당 논문에서 쓰이는 맥락으로 번역을 해보면 맞추다, 조정하다 정도로 해석할 수 있을 것 같습니다

## 2. Definitions
- supervised multiclass classification with neural network 대상
![스크린샷, 2021-02-24 17-27-51](https://user-images.githubusercontent.com/24715877/108971432-a7284080-76c5-11eb-8835-ef95c87d41fb.png)
- accuracy와 confidence를 각각 위 식의 좌변과 우변의 근사치로 쓸 수 있는데, 두 값이 서로 완벽하게 같으면 calibrated 된 것
### Reliability Diagram: 모델 calibration을 시각화해주는 표현방식
![스크린샷, 2021-02-24 17-30-21](https://user-images.githubusercontent.com/24715877/108971808-08501400-76c6-11eb-91df-f7ee91250442.png)
### Expected Calibration Error (ECE): scalar summary statistics of calibration
![스크린샷, 2021-02-24 17-32-04](https://user-images.githubusercontent.com/24715877/108972021-40efed80-76c6-11eb-96fd-42df5eb60989.png)
- 예측을 M개로 쪼개서 각각의 bin들의 가중 평균을 구함
- acc와 conf의 차이가 calibration gap
### Maximum Calibration Error (MCE): confidence와 accuracy의 차이를 줄이려는 목적
- 모든 bin(예측을 M개의 bin으로 쪼갬)들 중에서 calibration gap이 가장 큰 bin
- ECE는 모든 gap의 가중평균
