### ISSUE TITLE
faiss 학습코드 작성

### ISSUE THREAD

**Issue by hyunwoongko** [dialobot/dialobot#25]

**Comment by jayden5744** [comment]
todo : nlist, nprobe 기본값 설정
- nprobe : the number of cells (out of nlist) that are visited to perform a search
- nlist : the number of cells
    - nlist =100으로 잡고 문장을 추가하면 다음과 같은 에러발생
    - Error: 'nx >= k' failed: Number of training points (1) should be at least as large as number of clusters (100)
    - Solution 1 : nlist 크기만큼 데이터셋을 한번에 학습을 해야함 => default dataset이 필요
    -  Solution 2 : 데이터가 100개 이하일 때는 문장이 추가될때마다 문장 개수와 동일한 nlist를 가진 index를 새로 생성, 100개 이후에는 기존의 index에 추가 데이터를 그대로 학습

**Comment by hyunwoongko** [comment]
intent 코드 많이 바꿨어요.
확인 부탁드려용

**Comment by hyunwoongko** [comment]
완료
