### ISSUE TITLE
slot2generation 데이터 조사

### ISSUE THREAD

**Issue by hyunwoongko** [dialobot/dialobot#27]
table to text generation 데이터셋을 사용하면 좋을 것 같은데요.
영어는 많이 있을텐데, 한국어나 중국어, 일본어 데이터는 조사를 해봐야 할 듯 하네요.

**Comment by MrBananaHuman** [comment]
<img width="667" alt="image" src="https://user-images.githubusercontent.com/34882690/113110804-74ccae80-9242-11eb-8b04-ea9156e82fea.png">
